<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@page isELIgnored="false"%>
<%@include file="header.jsp"%>
<%@page import="com.project.Model.*"%>
<%@page import="java.util.*"%>

<br>
<br>
<br>
<br>
<br>
<body>
	<div class="container">
		<div class="row">
			<form action="${pageContext.request.contextPath}/cartAdd">
				<c:forEach var="pro" items="${prolist}">
					<div class="col-xs-5 item-photo">
						<img style="max-width: 100%;" src="./resources/${pro.imgname}" />
					</div>
					<div class="col-xs-7" style="border: 0px solid gray">
						<input type="hidden" name="pid" value="${pro.pid }" />
						<h5 style="color: #337ab7">${pro.pname}</h5>
						<h5 style="color: #337ab7">${pro.category.cname}</h5>
						<h5 style="color: #337ab7">Price : ${pro.price}</h5>
						<h5 style="color: #337ab7">Supplier : ${pro.supplier.sname}</h5>
						<h5 style="color: #337ab7">

							Qty : <select name="qty">
								<c:forEach var="i" begin="1" end="${pro.stock}">
									<option value="${i}">${i}</option>
								</c:forEach>
							</select>

						</h5>
						<input type="submit" value="Add to Cart" />
				</c:forEach>
		</div>
		</form>
		<br> <br> <br> <br>
		<div class="col-xs-9">
			<div style="width: 100%; border-top: 1px silver">
				<p style="padding: 10px;">
					<small>
						<ul>
							<li>This document is an electronic record in terms of
								Information Technology Act, 2000 and rules there under as
								applicable and the amended provisions pertaining to electronic
								records in various statutes as amended by the Information
								Technology Act, 2000.</li>
							<li>This electronic record is generated by a computer system
								and does not require any physical or digital signatures.</li>
							<li>This document is published in accordance with the
								provisions of Rule 3 (1) of the Information Technology
								(Intermediaries guidelines) Rules, 2011 that require publishing
								the rules and regulations, privacy policy and Terms of Use for
								access</li>

						</ul>
					</small>
				</p>
			</div>
		</div>
	</div>


</body>
<%@include file="footer.jsp"%>